version: "3.9"
services:
  rabbitmq:
    networks:
      - docker-rabbit
    image: rabbitmq:3-management
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../rabbitmq_data:/var/lib/rabbitmq

  database:
    networks:
      - docker-rabbit
    image: postgres
    restart: always
    container_name: database_rabbit
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rabbit
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - "20001:5432"

networks:
  docker-rabbit:
    driver: bridge
    external: true
